
-- Task3 : 
--Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue

SELECT a.name AS "Category Name", SUM(c.quantity * c.unit_price) AS total_revenue
FROM Categories a
INNER JOIN Products b ON a.category_id = b.category_id
INNER JOIN Order_Items c ON b.product_id = c.product_id
GROUP BY a.name
ORDER BY total_revenue DESC;
